-- MySQL Script generated by MySQL Workbench
-- Tue Oct  3 09:04:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BD_ProyCort2Prog3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD_ProyCort2Prog3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_ProyCort2Prog3` DEFAULT CHARACTER SET utf8 ;
USE `BD_ProyCort2Prog3` ;

-- -----------------------------------------------------
-- Table `BD_ProyCort2Prog3`.`semester`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ProyCort2Prog3`.`semester` (
  `idsemester` INT NOT NULL AUTO_INCREMENT,
  `finalScore` FLOAT NULL,
  PRIMARY KEY (`idsemester`),
  UNIQUE INDEX `idsemester_UNIQUE` (`idsemester` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ProyCort2Prog3`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ProyCort2Prog3`.`subject` (
  `idsubject` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NOT NULL,
  `finalScore` FLOAT NULL,
  `semester_idsemester` INT NOT NULL,
  PRIMARY KEY (`idsubject`),
  UNIQUE INDEX `idsubject_UNIQUE` (`idsubject` ASC),
  INDEX `fk_subject_semester1_idx` (`semester_idsemester` ASC),
  CONSTRAINT `fk_subject_semester1`
    FOREIGN KEY (`semester_idsemester`)
    REFERENCES `BD_ProyCort2Prog3`.`semester` (`idsemester`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ProyCort2Prog3`.`activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ProyCort2Prog3`.`activity` (
  `idactivity` INT NOT NULL AUTO_INCREMENT,
  `activityType` VARCHAR(45) NOT NULL,
  `weighted` FLOAT NOT NULL,
  `deadLine` DATE NOT NULL,
  `score` FLOAT NULL,
  `state` ENUM('Pendiente', 'En desarrollo', 'Terminado', 'Entregado') NOT NULL,
  `subject_idsubject` INT NOT NULL,
  PRIMARY KEY (`idactivity`),
  UNIQUE INDEX `idactivity_UNIQUE` (`idactivity` ASC),
  INDEX `fk_activity_subject1_idx` (`subject_idsubject` ASC),
  CONSTRAINT `fk_activity_subject1`
    FOREIGN KEY (`subject_idsubject`)
    REFERENCES `BD_ProyCort2Prog3`.`subject` (`idsubject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
